<a href="https://colab.research.google.com/github/emmanuelmassawe/THIS-IS-A-SPEECH-TO-TEXT-TRANSFORMER-USING-HUGGING-FACE/blob/main/speech_to_text_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# THIS IS A SPEECH TO TEXT  TRANSFORMER USING HUGGING **FACE**

we intialize our libraries

In [3]:
pip install transformers

In [4]:
import transformers
import torch
import librosa
import IPython.display as ipd
from transformers import Wav2Vec2ForCTC, Wav2Vec2Processor
import numpy as np
from transformers import pipeline


we load our pretrained models

In [5]:
tokenizer = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-base-960h")
model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")

Loading weights:   0%|          | 0/212 [00:00<?, ?it/s]

[transformers] Wav2Vec2ForCTC LOAD REPORT from: facebook/wav2vec2-base-960h
Key                        | Status  | 
---------------------------+---------+-
wav2vec2.masked_spec_embed | MISSING | 

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


In [6]:
audio, sampling_rate = librosa.load("/content/harvard.wav", sr = 16000)
audio ,sampling_rate

(array([ 1.5941411e-06, -1.0580342e-05, -3.1768568e-06, ...,
        -1.9331981e-03, -1.8884519e-03,  0.0000000e+00], dtype=float32),
 16000)

In [7]:
ipd.Audio(audio, rate=sampling_rate)

In [8]:
input_values = tokenizer(audio, return_tensors="pt").input_values
input_values

[transformers] It is strongly recommended to pass the `sampling_rate` argument to `Wav2Vec2FeatureExtractor()`. Failing to do so can result in silent errors that might be hard to debug.


tensor([[ 1.3096e-04, -8.6395e-05,  4.5779e-05,  ..., -3.4411e-02,
         -3.3612e-02,  1.0250e-04]])

In [9]:
with torch.no_grad():
  logits = model(input_values, return_dict=True).logits
  logits

In [10]:
prediction = torch.argmax(logits, dim=-1)
prediction

tensor([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  6, 11, 11,  0,
          5,  0,  4,  4,  0,  0,  0, 12,  0,  6,  0,  0,  0,  0,  7,  0,  0,  0,
         15, 15,  5,  0,  0,  4,  4,  0,  0, 12,  0,  0,  0, 17,  0,  0,  0,  5,
          5, 15, 15,  0,  0, 15,  0,  0,  4,  4,  8, 20,  4,  4,  4,  4,  4,  0,
          0,  0,  0,  0,  0,  8,  0, 15, 15, 14, 14,  0,  4,  4,  0, 24,  0,  0,
          0,  5,  0,  5, 13, 13, 13,  0,  0,  4,  4,  0, 15, 15,  0,  0, 10,  9,
          0,  0, 21,  0,  0,  0,  5, 13, 13, 13,  0,  0,  0, 12,  0,  4,  4,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,

In [12]:
transcription = tokenizer.decode(prediction[0])
transcription

'THE STALE SMELL OF OLD BEER LINGERS IT TAKES HEAT TO BRING OUT THE ODOR A COLD DIP RESTORES HEALTH AND ZEST A SALT PICKLE TASTES FINE WITH HAM TAKOS AL PASTORE ARE MY FAVORITE A ZESTFUL FOOD IS THE HOT CROSS BUN'